apiVersion: batch/v1
kind: Job
metadata:
  name: loader
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: loader
        image: python:3.8-slim
        command:
        - "/scripts/loader.sh"
        env:
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: redis_url
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      volumes:
      - name: scripts
        configMap:
          name: loader-scripts
          defaultMode: 0744