apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: thesaurize-bot
  name: redis-statefulset
  labels:
    app: redis
spec:
  replicas: 1
  serviceName: redis
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        args:
        - "--appendonly"
        - "yes"
        - "--save"
        - "60"
        - "1"
        ports:
          - containerPort: 6379
        volumeMounts:
          - mountPath: /data
            name: datastore
        resources:
          limits:
            memory: 100Mi
            cpu: 100m
      volumes:
      - name: datastore
        persistentVolumeClaim:
          claimName: thesaurize-bot-datastore
---
apiVersion: v1
kind: Service
metadata:
  namespace: thesaurize-bot
  name: redis-service
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: thesaurize-bot
  name: redis-config
data:
  redis-url: redis-service