apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: thesaurize-bot
  name: thesaurize-bot-datastore
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage