project_name: thesaurize
version: 2
before:
  hooks:
    - go mod download
builds:
  - id: "default"
    env:
      - CGO_ENABLED=0
    binary: bot
    dir: ./cmd/bot
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .ShortCommit }} -X main.date={{ .Date }} -X main.skipCommonWords=true
    goos:
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - builds:
      - default
    wrap_in_directory: true
    files:
      - README.md
      - LICENSE
      - chart/*
dockers:
  - ids:
      - default
    image_templates:
      - "ghcr.io/mrflynn/{{ .ProjectName }}:latest-amd64"
      - "ghcr.io/mrflynn/{{ .ProjectName }}:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.licenses=${LICENSE_NAME}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=${GIT_URL}"
      - "--platform=linux/amd64"
  - ids:
      - default
    image_templates:
      - "ghcr.io/mrflynn/{{ .ProjectName }}:latest-arm64v8"
      - "ghcr.io/mrflynn/{{ .ProjectName }}:{{ .Version }}-arm64v8"
    use: buildx
    dockerfile: Dockerfile
    goarch: arm64
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.licenses=${LICENSE_NAME}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=${GIT_URL}"
      - "--platform=linux/arm64/v8"
docker_manifests:
  - name_template: "ghcr.io/mrflynn/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "ghcr.io/mrflynn/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/mrflynn/{{ .ProjectName }}:{{ .Version }}-arm64v8"
  - name_template: "ghcr.io/mrflynn/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/mrflynn/{{ .ProjectName }}:latest-amd64"
      - "ghcr.io/mrflynn/{{ .ProjectName }}:latest-arm64v8"
checksum:
  name_template: SHA256SUMS
snapshot:
  version_template: "{{ .ShortCommit }}-rc"
changelog:
  filters:
    exclude:
      - "^conf:"
      - "^test:"
      - "^docs:"
