before:
  hooks:
  - go mod download
builds:
- id: "default"
  env:
  - CGO_ENABLED=0
  binary: bot
  dir: ./cmd/bot
  ldflags:
  - -s -w -X main.version={{ .Version }} -X main.commit={{ .ShortCommit }} -X main.date={{ .Date }} -X main.skipCommonWords=true
  goos:
  - linux
  goarch:
  - amd64
  - arm64
  - arm
  goarm:
  - 7
archives:
- id: "default"
  builds:
  - "default"
  wrap_in_directory: true
dockers:
- ids:
  - default
  image_templates:
  - "mrflynn/thesaurize:latest-amd64"
  - "mrflynn/thesaurize:{{ .Version }}-amd64"
  - "ghcr.io/mrflynn/thesaurize:latest-amd64"
  - "ghcr.io/mrflynn/thesaurize:{{ .Version }}-amd64"
  use_buildx: true
  dockerfile: Dockerfile
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.created={{ .Date }}"
  - "--label=org.opencontainers.image.title=thesaurize"
  - "--label=org.opencontainers.image.licenses=MIT"
  - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
  - "--label=org.opencontainers.image.version={{ .Version }}"
  - "--platform=linux/amd64"
- ids:
  - default
  image_templates:
  - "mrflynn/thesaurize:latest-arm64v8"
  - "mrflynn/thesaurize:{{ .Version }}-arm64v8"
  - "ghcr.io/mrflynn/thesaurize:latest-arm64v8"
  - "ghcr.io/mrflynn/thesaurize:{{ .Version }}-arm64v8"
  use_buildx: true
  dockerfile: Dockerfile
  goarch: arm64
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.created={{ .Date }}"
  - "--label=org.opencontainers.image.title=thesaurize"
  - "--label=org.opencontainers.image.licenses=MIT"
  - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
  - "--label=org.opencontainers.image.version={{ .Version }}"
  - "--platform=linux/arm64/v8"
docker_manifests:
- name_template: "mrflynn/thesaurize:{{ .Version }}"
  image_templates:
  - "mrflynn/thesaurize:{{ .Version }}-amd64"
  - "mrflynn/thesaurize:{{ .Version }}-arm64v8"
- name_template: "mrflynn/thesaurize:latest"
  image_templates:
  - "mrflynn/thesaurize:latest-amd64"
  - "mrflynn/thesaurize:latest-arm64v8"
- name_template: "ghcr.io/mrflynn/thesaurize:{{ .Version }}"
  image_templates:
  - "ghcr.io/mrflynn/thesaurize:{{ .Version }}-amd64"
  - "ghcr.io/mrflynn/thesaurize:{{ .Version }}-arm64v8"
- name_template: "ghcr.io/mrflynn/thesaurize:latest"
  image_templates:
  - "ghcr.io/mrflynn/thesaurize:latest-amd64"
  - "ghcr.io/mrflynn/thesaurize:latest-arm64v8"
checksum:
  name_template: SHASUMS.txt
snapshot:
  name_template: "{{ .Tag }}-{{ .ShortCommit }}-RC"
changelog:
  sort: asc
  filters:
    exclude:
    - "^conf:"
    - "^test:"
    - "^docs:"