apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ .Values.redis.name }}
  labels:
    app: {{ .Values.redis.name }}
spec:
  replicas: 1
  serviceName: {{ .Values.redis.name }}
  selector:
    matchLabels:
      app: {{ .Values.redis.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.redis.name }}
    spec:
      containers:
      - name: {{ .Values.redis.name }}
        image: {{ .Values.redis.image }}
        args:
        - "--appendonly"
        - "yes"
        - "--save"
        - "60"
        - "1"
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /data
          name: datastore
        resources:
          limits:
            memory: 100Mi
            cpu: 100m
      volumes:
      - name: datastore
        persistentVolumeClaim:
          claimName: {{ .Values.redis.datastore.claimName }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ .Values.redis.name }}
spec:
  selector:
    app: {{ .Values.redis.name }}
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
