apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.thesaurize.apiToken.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  token: {{ required "A discord API token is required" .Values.thesaurize.apiToken.value | b64enc | quote }} 
