name: Loader tests

on:
  push:
    paths:
      - 'tools/loader-tool/**'
      - '.github/workflows/py-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8.0, 3.8.1]
        poetry-version: [1.0.0]
    steps:
      - uses: actions/checkout@v2
      - name: Run tests and linter checks
        uses: MrFlynn/actions-poetry@master
        with:
          python_version: ${{ matrix.python-version }}
          poetry_version: ${{ matrix.poetry-version }}
          working_directory: ./tools/loader-tool
          args:
            - install
            - poetry run python -m pytest -vv tests/
            - poetry run python -m black --check .