name: Loader tests

on:
  push:
    paths:
      - 'tools/loader-tool/**'
      - '.github/workflows/py-ci.yml'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.3'
          architecture: x64
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
      - name: Install dependencies
        run: |
          source $HOME/.poetry/env
          cd ./tools/loader-tool
          
          poetry install
      - name: Run unit tests and linter checks
        run: |
          source $HOME/.poetry/env
          cd ./tools/loader-tool

          poetry run python -m pytest -vv tests/
          poetry run python -m black --check .
      - name: Build wheel
        run: |
          source $HOME/.poetry/env
          cd ./tools/loader-tool

          poetry build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: loader-tool-wheel
          path: tools/loader-tool/dist/thesaurize_loader-[0-9].[0-9].[0-9]-py3-none-any.whl