name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - uses: docker/login-action@v1
        with:
          username: mrflynn
          password: ${{ secrets.DOCKER_REGISTRY_KEY }}
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: mrflynn
          password: ${{ secrets.CR_PAT }}
      - uses: actions/download-artifact@v2
        with:
          name: loader-tool-wheel
          path: artifacts
      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
