name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - name: Login to hub.docker.com
        uses: azure/docker-login@v1
        with:
          username: mrflynn
          password: ${{ secrets.DOCKER_REGISTRY_KEY }}
      - name: Login to ghcr.io
        uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: mrflynn
          password: ${{ secrets.CR_PAT }}
      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}